-- ============================================================
-- NomadHub Snowflake Setup — Step 01: Foundation
-- ============================================================
-- Run this script in Snowsight as ACCOUNTADMIN (or SYSADMIN)
-- Execute statements one section at a time.
-- ============================================================

-- ── 1. Virtual Warehouse ───────────────────────────────────────────────────────
CREATE WAREHOUSE IF NOT EXISTS NOMAD_WH
    WAREHOUSE_SIZE   = 'X-SMALL'
    AUTO_SUSPEND     = 120           -- suspend after 2 minutes idle
    AUTO_RESUME      = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 2            -- auto-scale for heavy dbt runs
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'NomadHub pipeline warehouse';

-- ── 2. Database ────────────────────────────────────────────────────────────────
CREATE DATABASE IF NOT EXISTS NOMAD_HUB
    DATA_RETENTION_TIME_IN_DAYS = 7
    COMMENT = 'NomadHub travel & booking data platform';

-- ── 3. Schemas (Medallion layers) ─────────────────────────────────────────────
USE DATABASE NOMAD_HUB;

CREATE SCHEMA IF NOT EXISTS RAW
    DATA_RETENTION_TIME_IN_DAYS = 7
    COMMENT = 'Bronze layer — raw COPY INTO tables from S3';

CREATE SCHEMA IF NOT EXISTS STAGING
    DATA_RETENTION_TIME_IN_DAYS = 3
    COMMENT = 'Silver layer — cleaned & typed dbt staging views';

CREATE SCHEMA IF NOT EXISTS MARTS
    DATA_RETENTION_TIME_IN_DAYS = 7
    COMMENT = 'Gold layer — dims, incremental facts, business marts';

CREATE SCHEMA IF NOT EXISTS AI
    DATA_RETENTION_TIME_IN_DAYS = 7
    COMMENT = 'AI layer — Gemini enrichment, embeddings, insights';

-- ── 4. Roles ───────────────────────────────────────────────────────────────────
-- NOMAD_ADMIN : full control (pipelines, DDL)
-- DBT_ROLE    : read RAW, write STAGING + MARTS + AI (transform only)
-- ANALYST_ROLE: read-only MARTS + AI (BI tools, Streamlit)

CREATE ROLE IF NOT EXISTS NOMAD_ADMIN  COMMENT = 'Full admin for NomadHub pipeline';
CREATE ROLE IF NOT EXISTS DBT_ROLE     COMMENT = 'dbt transform — write STAGING/MARTS/AI, read RAW';
CREATE ROLE IF NOT EXISTS ANALYST_ROLE COMMENT = 'Read-only access to MARTS and AI schemas';

-- Role hierarchy
GRANT ROLE NOMAD_ADMIN  TO ROLE SYSADMIN;
GRANT ROLE DBT_ROLE     TO ROLE NOMAD_ADMIN;
GRANT ROLE ANALYST_ROLE TO ROLE NOMAD_ADMIN;

-- ── 5. Warehouse grants ────────────────────────────────────────────────────────
GRANT USAGE ON WAREHOUSE NOMAD_WH TO ROLE NOMAD_ADMIN;
GRANT USAGE ON WAREHOUSE NOMAD_WH TO ROLE DBT_ROLE;
GRANT USAGE ON WAREHOUSE NOMAD_WH TO ROLE ANALYST_ROLE;

-- ── 6. Database & schema grants ────────────────────────────────────────────────
GRANT USAGE ON DATABASE NOMAD_HUB TO ROLE NOMAD_ADMIN;
GRANT USAGE ON DATABASE NOMAD_HUB TO ROLE DBT_ROLE;
GRANT USAGE ON DATABASE NOMAD_HUB TO ROLE ANALYST_ROLE;

-- NOMAD_ADMIN: all schemas
GRANT ALL ON ALL SCHEMAS IN DATABASE NOMAD_HUB TO ROLE NOMAD_ADMIN;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE NOMAD_HUB TO ROLE NOMAD_ADMIN;

-- DBT_ROLE: read RAW, full access to STAGING/MARTS/AI
GRANT USAGE ON SCHEMA NOMAD_HUB.RAW     TO ROLE DBT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA NOMAD_HUB.RAW TO ROLE DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NOMAD_HUB.RAW TO ROLE DBT_ROLE;

GRANT ALL PRIVILEGES ON SCHEMA NOMAD_HUB.STAGING TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA NOMAD_HUB.MARTS   TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA NOMAD_HUB.AI      TO ROLE DBT_ROLE;

GRANT ALL ON ALL TABLES IN SCHEMA NOMAD_HUB.STAGING TO ROLE DBT_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA NOMAD_HUB.MARTS   TO ROLE DBT_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA NOMAD_HUB.AI      TO ROLE DBT_ROLE;

GRANT ALL ON FUTURE TABLES IN SCHEMA NOMAD_HUB.STAGING TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA NOMAD_HUB.MARTS   TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA NOMAD_HUB.AI      TO ROLE DBT_ROLE;

-- ANALYST_ROLE: read-only MARTS + AI
GRANT USAGE ON SCHEMA NOMAD_HUB.MARTS TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA NOMAD_HUB.AI    TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA NOMAD_HUB.MARTS TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA NOMAD_HUB.AI    TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NOMAD_HUB.MARTS TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NOMAD_HUB.AI    TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA NOMAD_HUB.MARTS  TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA NOMAD_HUB.MARTS TO ROLE ANALYST_ROLE;

-- ── 7. Service users ───────────────────────────────────────────────────────────
-- Create dedicated users for each role (replace passwords!)
CREATE USER IF NOT EXISTS NOMAD_PIPELINE_USER
    PASSWORD            = 'CHANGE_ME_STRONG_PASSWORD_1!'
    DEFAULT_ROLE        = NOMAD_ADMIN
    DEFAULT_WAREHOUSE   = NOMAD_WH
    DEFAULT_NAMESPACE   = NOMAD_HUB
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT = 'Service user for Airflow pipeline';

CREATE USER IF NOT EXISTS DBT_SERVICE_USER
    PASSWORD            = 'CHANGE_ME_STRONG_PASSWORD_2!'
    DEFAULT_ROLE        = DBT_ROLE
    DEFAULT_WAREHOUSE   = NOMAD_WH
    DEFAULT_NAMESPACE   = NOMAD_HUB
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT = 'Service user for dbt transformations';

CREATE USER IF NOT EXISTS ANALYST_USER
    PASSWORD            = 'CHANGE_ME_STRONG_PASSWORD_3!'
    DEFAULT_ROLE        = ANALYST_ROLE
    DEFAULT_WAREHOUSE   = NOMAD_WH
    DEFAULT_NAMESPACE   = NOMAD_HUB
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT = 'Service user for Streamlit / BI tools';

GRANT ROLE NOMAD_ADMIN  TO USER NOMAD_PIPELINE_USER;
GRANT ROLE DBT_ROLE     TO USER DBT_SERVICE_USER;
GRANT ROLE ANALYST_ROLE TO USER ANALYST_USER;

-- ── Verification ───────────────────────────────────────────────────────────────
SHOW WAREHOUSES LIKE 'NOMAD%';
SHOW DATABASES LIKE 'NOMAD%';
SHOW SCHEMAS IN DATABASE NOMAD_HUB;
SHOW ROLES LIKE 'NOMAD%';
SHOW ROLES LIKE 'DBT%';
SHOW ROLES LIKE 'ANALYST%';
