-- =====================================================================
-- NomadHub — load RAW from the S3 stage
-- COPY INTO remembers which files it has loaded (64-day load metadata), so re-running
-- this script loads only NEW files — e.g. a new monthly BTS file or a new Airbnb
-- snapshot. That is what makes the daily Airflow run incremental.
-- Run as LOADER_ROLE after snowflake/01_raw_tables.sql.
-- =====================================================================
USE ROLE LOADER_ROLE;
USE WAREHOUSE NOMAD_WH;
USE SCHEMA NOMAD_HUB.RAW;

-- countries (6 columns)
COPY INTO COUNTRIES (ID, CODE, NAME, CONTINENT, WIKIPEDIA_LINK, KEYWORDS, _SOURCE_FILE, _LOADED_AT)
FROM (
    SELECT $1, $2, $3, $4, $5, $6,
           METADATA$FILENAME, CURRENT_TIMESTAMP()
    FROM @RAW_STAGE/countries/
)
PATTERN = '.*[.]csv[.]gz'
ON_ERROR = 'ABORT_STATEMENT';

-- regions (8 columns)
COPY INTO REGIONS (ID, CODE, LOCAL_CODE, NAME, CONTINENT, ISO_COUNTRY, WIKIPEDIA_LINK, KEYWORDS, _SOURCE_FILE, _LOADED_AT)
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8,
           METADATA$FILENAME, CURRENT_TIMESTAMP()
    FROM @RAW_STAGE/regions/
)
PATTERN = '.*[.]csv[.]gz'
ON_ERROR = 'ABORT_STATEMENT';

-- airports (19 columns)
COPY INTO AIRPORTS (ID, IDENT, TYPE, NAME, LATITUDE_DEG, LONGITUDE_DEG, ELEVATION_FT, CONTINENT, ISO_COUNTRY, ISO_REGION, MUNICIPALITY, SCHEDULED_SERVICE, ICAO_CODE, IATA_CODE, GPS_CODE, LOCAL_CODE, HOME_LINK, WIKIPEDIA_LINK, KEYWORDS, _SOURCE_FILE, _LOADED_AT)
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19,
           METADATA$FILENAME, CURRENT_TIMESTAMP()
    FROM @RAW_STAGE/airports/
)
PATTERN = '.*[.]csv[.]gz'
ON_ERROR = 'ABORT_STATEMENT';

-- listings (46 columns)
COPY INTO LISTINGS (CITY, SNAPSHOT_DATE, LISTING_ID, LAST_SCRAPED, NAME, DESCRIPTION, HOST_ID, HOST_SINCE, HOST_RESPONSE_RATE, HOST_ACCEPTANCE_RATE, HOST_IS_SUPERHOST, CALCULATED_HOST_LISTINGS_COUNT, NEIGHBOURHOOD_CLEANSED, NEIGHBOURHOOD_GROUP_CLEANSED, LATITUDE, LONGITUDE, PROPERTY_TYPE, ROOM_TYPE, ACCOMMODATES, BATHROOMS, BATHROOMS_TEXT, BEDROOMS, BEDS, AMENITIES, PRICE, MINIMUM_NIGHTS, MAXIMUM_NIGHTS, HAS_AVAILABILITY, AVAILABILITY_30, AVAILABILITY_90, AVAILABILITY_365, NUMBER_OF_REVIEWS, NUMBER_OF_REVIEWS_LTM, FIRST_REVIEW, LAST_REVIEW, REVIEW_SCORES_RATING, REVIEW_SCORES_ACCURACY, REVIEW_SCORES_CLEANLINESS, REVIEW_SCORES_CHECKIN, REVIEW_SCORES_COMMUNICATION, REVIEW_SCORES_LOCATION, REVIEW_SCORES_VALUE, INSTANT_BOOKABLE, LICENSE, ESTIMATED_OCCUPANCY_L365D, ESTIMATED_REVENUE_L365D, _SOURCE_FILE, _LOADED_AT)
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39, $40, $41, $42, $43, $44, $45, $46,
           METADATA$FILENAME, CURRENT_TIMESTAMP()
    FROM @RAW_STAGE/listings/
)
PATTERN = '.*[.]csv[.]gz'
ON_ERROR = 'ABORT_STATEMENT';

-- calendar (7 columns)
COPY INTO CALENDAR (CITY, SNAPSHOT_DATE, LISTING_ID, CALENDAR_DATE, AVAILABLE, MINIMUM_NIGHTS, MAXIMUM_NIGHTS, _SOURCE_FILE, _LOADED_AT)
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7,
           METADATA$FILENAME, CURRENT_TIMESTAMP()
    FROM @RAW_STAGE/calendar/
)
PATTERN = '.*[.]csv[.]gz'
ON_ERROR = 'ABORT_STATEMENT';

-- reviews (7 columns)
COPY INTO REVIEWS (CITY, SNAPSHOT_DATE, REVIEW_ID, LISTING_ID, REVIEW_DATE, REVIEWER_ID, COMMENTS, _SOURCE_FILE, _LOADED_AT)
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7,
           METADATA$FILENAME, CURRENT_TIMESTAMP()
    FROM @RAW_STAGE/reviews/
)
PATTERN = '.*[.]csv[.]gz'
ON_ERROR = 'ABORT_STATEMENT';

-- flights (37 columns)
COPY INTO FLIGHTS (FLIGHT_DATE, REPORTING_AIRLINE, AIRLINE_IATA_CODE, TAIL_NUMBER, FLIGHT_NUMBER, ORIGIN, ORIGIN_CITY_NAME, ORIGIN_STATE, DEST, DEST_CITY_NAME, DEST_STATE, CRS_DEP_TIME, DEP_TIME, DEP_DELAY, DEP_DELAY_MINUTES, DEP_DEL15, TAXI_OUT, WHEELS_OFF, WHEELS_ON, TAXI_IN, CRS_ARR_TIME, ARR_TIME, ARR_DELAY, ARR_DELAY_MINUTES, ARR_DEL15, CANCELLED, CANCELLATION_CODE, DIVERTED, CRS_ELAPSED_TIME, ACTUAL_ELAPSED_TIME, AIR_TIME, DISTANCE, CARRIER_DELAY, WEATHER_DELAY, NAS_DELAY, SECURITY_DELAY, LATE_AIRCRAFT_DELAY, _SOURCE_FILE, _LOADED_AT)
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37,
           METADATA$FILENAME, CURRENT_TIMESTAMP()
    FROM @RAW_STAGE/flights/
)
PATTERN = '.*[.]csv[.]gz'
ON_ERROR = 'ABORT_STATEMENT';

-- users (13 columns)
COPY INTO USERS (USER_ID, SOURCE_REVIEWER_ID, FIRST_NAME, LAST_NAME, EMAIL, GENDER, BIRTH_DATE, HOME_COUNTRY_CODE, HOME_AIRPORT, PREFERRED_LANGUAGE, SIGNED_UP_AT, ACQUISITION_CHANNEL, MARKETING_OPT_IN, _SOURCE_FILE, _LOADED_AT)
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13,
           METADATA$FILENAME, CURRENT_TIMESTAMP()
    FROM @RAW_STAGE/users/
)
PATTERN = '.*[.]csv[.]gz'
ON_ERROR = 'ABORT_STATEMENT';

-- stay_bookings (20 columns)
COPY INTO STAY_BOOKINGS (STAY_BOOKING_ID, USER_ID, LISTING_ID, CITY, REVIEW_ID, BOOKED_AT, CHECKIN_DATE, CHECKOUT_DATE, NIGHTS, GUESTS, CURRENCY_CODE, NIGHTLY_RATE, CLEANING_FEE, SERVICE_FEE, TOTAL_AMOUNT, PAYMENT_METHOD, BOOKING_CHANNEL, BOOKING_STATUS, CANCELLED_AT, REFUND_AMOUNT, _SOURCE_FILE, _LOADED_AT)
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
           METADATA$FILENAME, CURRENT_TIMESTAMP()
    FROM @RAW_STAGE/stay_bookings/
)
PATTERN = '.*[.]csv[.]gz'
ON_ERROR = 'ABORT_STATEMENT';

-- flight_bookings (16 columns)
COPY INTO FLIGHT_BOOKINGS (FLIGHT_BOOKING_ID, STAY_BOOKING_ID, USER_ID, LEG, BOOKED_AT, FLIGHT_DATE, AIRLINE_CODE, FLIGHT_NUMBER, ORIGIN, DEST, CRS_DEP_TIME, CABIN_CLASS, PASSENGERS, FARE_PER_PASSENGER_USD, TOTAL_FARE_USD, BOOKING_STATUS, _SOURCE_FILE, _LOADED_AT)
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16,
           METADATA$FILENAME, CURRENT_TIMESTAMP()
    FROM @RAW_STAGE/flight_bookings/
)
PATTERN = '.*[.]csv[.]gz'
ON_ERROR = 'ABORT_STATEMENT';

-- ── Sanity check: compare with data/raw/_manifest.json ──────────────────
SELECT 'countries' AS tbl, COUNT(*) AS row_count FROM COUNTRIES
UNION ALL SELECT 'regions',         COUNT(*) FROM REGIONS
UNION ALL SELECT 'airports',        COUNT(*) FROM AIRPORTS
UNION ALL SELECT 'listings',        COUNT(*) FROM LISTINGS
UNION ALL SELECT 'calendar',        COUNT(*) FROM CALENDAR
UNION ALL SELECT 'reviews',         COUNT(*) FROM REVIEWS
UNION ALL SELECT 'flights',         COUNT(*) FROM FLIGHTS
UNION ALL SELECT 'users',           COUNT(*) FROM USERS
UNION ALL SELECT 'stay_bookings',   COUNT(*) FROM STAY_BOOKINGS
UNION ALL SELECT 'flight_bookings', COUNT(*) FROM FLIGHT_BOOKINGS
ORDER BY row_count DESC;
